# Path to your oh-my-zsh configuration.
ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="pygmalion"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(bundler docker docker-compose pip)

source "$ZSH/oh-my-zsh.sh"

# Customize to your needs...

. ~/.zsh/config
. ~/.zsh/aliases
. ~/.zsh/completion

# Set up pyenv
if [ -x "$(command -v pyenv)" ]; then
  eval "$(pyenv init -)"
fi

# Set up rbenv
if [ -x "$(command -v rbenv)" ]; then
  eval "$(rbenv init -)"
fi

# Set up aws completions
if [ -x "$(command -v aws_zsh_completer.sh)" ]; then
  source "$(command -v aws_zsh_completer.sh)"
fi

# Display MotD
if [[ -f /etc/motd ]]; then
  if [[ -f "${HOME}/.config/dotfiles/motd_check" ]]; then
    motd_updated=$(stat --format="%Y" /etc/motd)
    if [[ "${motd_updated}" > "$(cat "${HOME}/.config/dotfiles/motd_check")" ]]; then
      date +%s > "${HOME}/.config/dotfiles/motd_check"
      echo -e "MotD: $(stat --format="%y" /etc/motd)\n"
      cat /etc/motd
    fi
  else
    mkdir -p "${HOME}/.config/dotfiles"
    date +%s > "${HOME}/.config/dotfiles/motd_check"
    echo -e "MotD: $(stat --format="%y" /etc/motd)\n"
    cat /etc/motd
  fi
fi

# use .localrc for settings specific to one system
[[ -f ~/.localrc ]] && . ~/.localrc
